### ISSUE TITLE
Mulig å merge branch til master uten at PR blir grønn

### ISSUE THREAD

**Issue by mrsladek** [navikt/fp-formidling#710]
Oppsettet på repo bør fikses.

**Comment by jejohnsen** [comment]
Vi regner med du mener "Require status checks to pass before merging" som ikke var huket av for master? Jeg har nå huket av for den, og "build" som dukket opp som underpunkt.

**Comment by mrsladek** [comment]
Ja og Require pull request reviews before merging hvis dere driver med reviews.
